all:
	pak -f pak2.pak -c \
		demo.cfg \
		slime.cfg \
		timer_aliases.cfg \
		timer_binds.cfg \
		tot_aliases.cfg \
		tot_binds.cfg \
		gfx.wad \
		skins/red.png \
		skins/white.png \
		gfx/conback.lmp \
		gfx/ranking.lmp \
		textures/charsets/povo5f_xtm.png
